name: "caldav"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  radicale:
    image: "11notes/radicale:3.6.0"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      RADICALE_RIGHTS: |-
        [_]
        user: .+
        collection:
        permissions: R

        [user]
        user: .+
        collection: {user}
        permissions: RW

        [user-inherit]
        user: .+
        collection: {user}/[^/]+
        permissions: rw
      RADICALE_USERS: |-
        admin:$$argon2i$$v=19$$m=16,t=2,p=1$$YzUzMjQyMzUz$$ZsEZ3NpmuKPRJ92gfuzZRA
    ports:
      - "3000:5232/tcp"
    networks:
      frontend:
    volumes:
      - "radicale.etc:/radicale/etc"
      - "radicale.var:/radicale/var"
    restart: "always"

volumes:
  radicale.etc:
  radicale.var:

networks:
  frontend: